# Generated by Django 5.1 on 2024-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinucleotides',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('Chromosome', models.CharField(blank=True, db_column='Chromosome No', max_length=100, null=True)),
                ('SSRtype', models.CharField(blank=True, db_column='SSR type', max_length=100, null=True)),
                ('SSRsequence', models.CharField(blank=True, db_column='SSR sequence', max_length=10000, null=True)),
                ('Size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('Start', models.IntegerField(blank=True, db_column='Start', null=True)),
                ('End', models.IntegerField(blank=True, db_column='End', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hexanucleotides',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('Chromosome', models.CharField(blank=True, db_column='Chromosome No', max_length=100, null=True)),
                ('SSRtype', models.CharField(blank=True, db_column='SSR type', max_length=100, null=True)),
                ('SSRsequence', models.CharField(blank=True, db_column='SSR sequence', max_length=10000, null=True)),
                ('Size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('Start', models.IntegerField(blank=True, db_column='Start', null=True)),
                ('End', models.IntegerField(blank=True, db_column='End', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mononucleotides',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('Chromosome', models.CharField(blank=True, db_column='Chromosome No', max_length=100, null=True)),
                ('SSRtype', models.CharField(blank=True, db_column='SSR type', max_length=100, null=True)),
                ('SSRsequence', models.CharField(blank=True, db_column='SSR sequence', max_length=10000, null=True)),
                ('Size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('Start', models.IntegerField(blank=True, db_column='Start', null=True)),
                ('End', models.IntegerField(blank=True, db_column='End', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pentanucleotides',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('Chromosome', models.CharField(blank=True, db_column='Chromosome No', max_length=100, null=True)),
                ('SSRtype', models.CharField(blank=True, db_column='SSR type', max_length=100, null=True)),
                ('SSRsequence', models.CharField(blank=True, db_column='SSR sequence', max_length=10000, null=True)),
                ('Size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('Start', models.IntegerField(blank=True, db_column='Start', null=True)),
                ('End', models.IntegerField(blank=True, db_column='End', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tetranucleotides',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('Chromosome', models.CharField(blank=True, db_column='Chromosome No', max_length=100, null=True)),
                ('SSRtype', models.CharField(blank=True, db_column='SSR type', max_length=100, null=True)),
                ('SSRsequence', models.CharField(blank=True, db_column='SSR sequence', max_length=10000, null=True)),
                ('Size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('Start', models.IntegerField(blank=True, db_column='Start', null=True)),
                ('End', models.IntegerField(blank=True, db_column='End', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trinucleotides',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('Chromosome', models.CharField(blank=True, db_column='Chromosome No', max_length=100, null=True)),
                ('SSRtype', models.CharField(blank=True, db_column='SSR type', max_length=100, null=True)),
                ('SSRsequence', models.CharField(blank=True, db_column='SSR sequence', max_length=10000, null=True)),
                ('Size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('Start', models.IntegerField(blank=True, db_column='Start', null=True)),
                ('End', models.IntegerField(blank=True, db_column='End', null=True)),
            ],
        ),
    ]
